name: Create a Release with signed SLSA Provenance

on: push

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: target
        output_path: $GITHUB_WORKSPACE/build.provenance

    - name: Push provenance to remote
      uses: actions/checkout@v3
      with:
        repository: siberov/action-store
        token: ${{ secrets.PAT }}
      env:
        TOKEN: ${{ secrets.PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Target repo to upload provenence file 
        URL: https://siberov:${{secrets.PAT}}@github.com/siberov/action-store
      run: |
        git config --global user.name 'action bot'
        git config --global user.email 'siberov@users.noreply.github.com'
        git commit -am "Automated report"
        git push


#    - name: Create Release
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: target/*
#        file_glob: true
#        tag: ${{ github.ref }}
#        overwrite: true
