name: Create a Release with signed SLSA Provenance

on: push

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: target
        output_path: build.provenance
    - name: Push provenance to remote
      env:
        TOKEN: ${{ secrets.PAT }}
        # Target repo to upload provenence file 
        URL: https://siberov:${{secrets.PAT}}@github.com/siberov/action-store
      run: |
        git config --global user.name "provenance-bot"
        git config --global user.email "dummy@email.com"
        git config --unset-all http.https://github.com/.extraheader
        git clone $URL
        echo "Cloned!"
        cp build.provenance action-store
        echo "Copied build.provenance into action-store"
        cd action-store
        echo "Changed directory to action-store"
        git add build.provenance
        git commit -m "${{ github.sha }}"
        echo "Committed"
        git remote set-url origin $URL
        git push
