name: Create a Release with signed SLSA Provenance

on: push

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: target
        output_path: build.provenance
        src_branch: store
        dst_branch: main
        commit_message: Provenance for ${{ GITHUB_SHA }}
    - name: Push provenance to remote
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PAT }}
        src_path: build.provenance
        dst_owner: siberov
        dst_repo_name: action-store
        src_branch: main
        dst_branch: main
