name: Create a Release with signed SLSA Provenance

on: push

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: target
        output_path: target/build.provenance

    - name: Push provenance to remote
      env:
        TOKEN: ${{ secrets.PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: https://siberov:${{secrets.PAT}}@github.com/siberov/action-store
      run: |
        git config --global user.name "provenance-bot"
        git config --global user.email "dummy@email.com"
        git config --unset-all http.https://github.com/.extraheader
        git clone $URL
        cp target/build.provenance action-store
        cd action-store
        git add build.provenance
        git commit -m "$GITHUB_SHA"
        git remote set-url origin $URL
        git push

#    - name: Create Release
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: target/*
#        file_glob: true
#        tag: ${{ github.ref }}
#        overwrite: true
