name: Create a Release with signed SLSA Provenance

on: push

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - name: Add SSH private key to agent
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PRIVATE_SSH_DEPLOY }}"
    - name: Push provenance to remote
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        # Target repo to upload provenence file 
        URL: git@github.com:siberov/action-store.git
      run: |
        git config --global user.name "provenance-bot"
        git config --global user.email "arvidsiberov+bot@outlook.com"
        git clone $URL
        cp build.provenance action-store
        cd action-store
        git add build.provenance
        git commit -m "${{ github.sha }}"
        git push
