name: Create a Release with signed SLSA Provenance

on: push

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: target
        output_path: build.provenance
    - name: Add SSH private key to agent
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PRIVATE_SSH_DEPLOY }}"
    - name: Push provenance to remote
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        # Target repo to upload provenence file 
        URL: git@github.com:siberov/action-store.git
      run: |
        git config --global user.name "provenance-bot"
        git config --global user.email "arvidsiberov+bot@outlook.com"
        git clone $URL
        cp build.provenance action-store
        cd action-store
        git add build.provenance
        git commit -m "${{ github.sha }}"
        git push
